### ISSUE TITLE
can't figure it out... maybe make this a q/a thread incase others have issues?

### ISSUE THREAD

**Issue by keiraxlicious** [josmoo/AmuletOfChemistryAlerter#2]
tried using the id feature. no luck
RANARR_POTION_UNF,PRAYER_POTION4_20393,PRAYER_POTION4
followed the instructions, but I just want a ping or a windows popup saying it broke or something.
depending on the coding language i might be able to help fix it

**Comment by josmoo** [comment]
I can make a youtube video for it if that'd help but I still need to get around to updating everything anyways first. 

I'm not sure what you're doing incorrectly but a few things to note: If you want to alert by specific potions only, you'll need to check "Notify by ID" and enter the IDs you want to notify for the potions you don't want to make without an amulet of chemistry. You only need to enter the ID, not the name. So for a prayer potion, you would want to do Ranarr potion (unf)'s ID which is 99. Most of the other IDs are found in the readme.md. I need to update the list and update the plugin to show the list on the support page for it, but in the meantime you can find it on the readme.md.

Otherwise if you don't have "Notify by ID" checked it will send an alert as long as you have an unf potion and its respective secondary for any potion.

Also it's open source if you want to make any changes.
